feat(update-macos-icons): added guard clause to check if fileicon installed

diff --git a/zsh/funcs/update-macos-icons b/zsh/funcs/update-macos-icons
--- a/zsh/funcs/update-macos-icons
+++ b/zsh/funcs/update-macos-icons
@@ -1,5 +1,11 @@
 #!/usr/bin/env zsh
 
+# Ensure fileicon installed
+command -v fileiconn || {
+  echo 'fileicon not found'
+  return 1
+}
+
 # Finder location: "/System/Library/CoreServices/Finder.app/Contents"
 local src="/System/Applications/$1.app/Contents"
 local tgt="$HOME/Applications/$1.app"
