feat(update-icons): added colored error message instead of installing from brew

diff --git a/zsh/funcs/update-icons b/zsh/funcs/update-icons
--- a/zsh/funcs/update-icons
+++ b/zsh/funcs/update-icons
@@ -1,11 +1,12 @@
 #!/usr/bin/env zsh
 
 # Create directory-icons association
-command -v fileicon &> /dev/null || brew install fileicon
+command -v fileicon &> /dev/null || { printf "${BRIGHTRED}%s %s${BRIGHTYELLOW}%s${RESET}\n" "" "'fileicon' dependency not found" " - please install or check in \$PATH."; return 1 }
 
 local table_width=60
 declare -A dir_icons=(
   /Applications/1Password.app            ~/Pictures/icons/1password-macos.png
+  /Applications/foobarz.app              ~/Pictures/icons/foobarz.png
   /Applications/ChatGPT.app              ~/Pictures/icons/chatgpt.png
   /Applications/Discord.app              ~/Pictures/icons/discord-macos.png
   /Applications/Docker.app               ~/Pictures/icons/docker.png
@@ -68,7 +69,7 @@ for dir in "${sorted_dirs[@]}"; do
 done
 
 # Footer
-local fail_count=$(($dir_count-$success_count))
+local fail_count=$(( dir_count - success_count ))
 
 print_separator
 printf "${GREEN}%-2s ${BRIGHTBLACK}%-37s${RESET}\n" "$success_count" 'Folder icon(s) updated successfully'
