feat(git): added escape condition for updating feature branches when no feature branches detected

diff --git a/zsh/funcs/update-feature-branches b/zsh/funcs/update-feature-branches
--- a/zsh/funcs/update-feature-branches
+++ b/zsh/funcs/update-feature-branches
@@ -6,17 +6,24 @@ local branches=("$@")
 # Dynamically fetch feature branches if no arguments are provided
 [[ $# -eq 0 ]] && branches=("${(@f)$(git branch --format='%(refname:short)' | grep '^feature/')}")
 
-for branch in "${branches[@]}"; do
-  # Check if branch exists
-  git branch --format='%(refname:short)' | grep -Fxq "$branch" || { printf "${RED}✘ '%s' not found${RESET} - run ${GREEN}'git branch'${RESET} to show available branches\n" "$branch"; continue; }
+if [[ ${#branches[@]} -eq 0 ]]; then
+  printf "${YELLOW}[WARN] no feature branches updated${RESET}\n"
+else
+  for branch in "${branches[@]}"; do
+    # Check if branch exists
+    if ! git branch --format='%(refname:short)' | grep -Fxq "$branch"; then
+      printf "${RED}[ERROR] '%s' not found${RESET} - run ${GREEN}'git branch'${RESET} to show available branches\n" "$branch"
+      continue
+    fi
 
-  # Perfom merge
-  git switch "$branch" &>/dev/null
-  git merge "$default" &>/dev/null
+    # Perform merge
+    git switch "$branch" &>/dev/null
+    git merge "$default" &>/dev/null
 
-  # Print success message after switching
-  printf "${GREEN}✔ ${RESET}${CYAN}%s${RESET} -> ${MAGENTA}${default}${RESET}\n" "$branch"
-done
+    # Print success message
+    printf "${GREEN}✔ ${RESET}${CYAN}%s${RESET} -> ${MAGENTA}${default}${RESET}\n" "$branch"
+  done
+fi
 
-# Return to main branch
+# Always return to main branch (once)
 git switch "$default" &>/dev/null
